In [33]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [34]:
df=pd.read_csv('data/dataset.csv')
df.head(5)

   compound  cbt_score    risk
0    -0.507          4  Medium
1     0.157          2     Low
2    -0.571          2  Medium
3    -0.603          3    High
4    -0.812          5    High

In [35]:
oe = OrdinalEncoder(categories=[["Low", "Medium", "High"]])
df["risk"]= oe.fit_transform(df[["risk"]])
df["risk"] = df["risk"].astype(int)
df.head(5)

   compound  cbt_score  risk
0    -0.507          4     1
1     0.157          2     0
2    -0.571          2     1
3    -0.603          3     2
4    -0.812          5     2

In [36]:
x=df.iloc[:,:-1]
y=df["risk"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [37]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 1501 to 1926
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   compound   1000 non-null   float64
 1   cbt_score  1000 non-null   int64
dtypes: float64(1), int64(1)
memory usage: 23.4 KB